[build]
  command = "npm ci && npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
