[build]
  # Enable corepack + install deps with pnpm + run your build
  command = "NODE_OPTIONS=--max_old_space_size=4096 corepack enable && pnpm install && pnpm run build:netlify"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.20.4"
  PNPM_VERSION = "9.4.0"
  NPM_FLAGS = "--legacy-peer-deps" # helps in case of peer dependency conflicts
  NODE_OPTIONS = "--max_old_space_size=4096" # Increase memory limit for build

# Cache dependencies & pnpm store between builds
[build.cache]
  paths = [
    "node_modules",
    ".pnpm-store",
    "packages/*/node_modules"
  ]

# Netlify Functions (serverless)
[functions]
  directory = "netlify/functions"

# Redirect API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for SPAs (React/Vite/etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
