[build]
  # Enable corepack + install deps with pnpm + run your build
  command = "corepack enable && pnpm install && pnpm run build:netlify"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9.15.9"
  NPM_FLAGS = "--legacy-peer-deps" # helps in case of peer dependency conflicts

# Cache dependencies & pnpm store between builds
[build.cache]
  paths = [
    "node_modules",
    ".pnpm-store",
    "packages/*/node_modules"
  ]

# Netlify Functions (serverless)
[functions]
  directory = "netlify/functions"

# Redirect API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for SPAs (React/Vite/etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
