[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_ENV = "production"

# Netlify Functions for server-side functionality
[functions]
  directory = "netlify/functions"

# Handle client-side routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
