[build]
  command = "echo 'Starting build process...' && npm --version && node --version && echo 'Installing dependencies...' && npm install --production=false && echo 'Dependencies installed successfully' && echo 'Starting build...' && npm run build && echo 'Build completed successfully'"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
