[build]
  command = "pnpm install && pnpm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.18.0"
  PNPM_VERSION = "8.15.6"
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
