[build]
  command = "rm -rf node_modules package-lock.json && npm cache clean --force && npm install --no-package-lock && npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
